Movie/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('imdb/', include('imdb.urls')),
]

imdb/urls.py
from django.urls import path

from . import views


app_name='imdb'
urlpatterns = [
    path('', views.index, name='index'),
    path('movieDetails', views.movieDetails, name='movieDetails'),
    path('addMovie', views.addMovie, name='addMovie'),
    path('editMovie', views.editMovie, name='editMovie'),
    path('moviesEdit', views.moviesEdit, name='moviesEdit'),
]

imdb/models.py
from django.db import models
from datetime import datetime  

# Create your models here.
class GenderChoice(models.Model):
	GENDER_CHOICES = (
		('M', "MALE"),
		('F', "FEMALE"),
	)
	gender = models.CharField(max_length=1, choices=GENDER_CHOICES,unique=True)
	def __str__(self):
		return self.gender

class Actors(models.Model):
	name = models.CharField(max_length=50,unique=True)
	sex= models.ForeignKey("GenderChoice", on_delete=models.CASCADE)
	DOB= models.DateField()
	bio=models.TextField(blank=True, null=True)
	def __str__(self):
		return self.name
	class Meta:
		verbose_name = "Actors"
		verbose_name_plural = "Actors"

class Producers(models.Model):
	name=models.CharField(max_length=50,unique=True)
	sex=models.ForeignKey("GenderChoice", on_delete=models.CASCADE)
	DOB=models.DateField()
	bio=models.TextField(blank=True, null=True)
	def __str__(self):
		return self.name
	class Meta:
		verbose_name = "Producers"
		verbose_name_plural = "Producers"

class Movies(models.Model):
	name=models.CharField(max_length=50,unique=True)
	year_of_release=models.PositiveIntegerField(default=2010)
	plot=models.TextField(blank=True, null=True)
	poster=models.ImageField(upload_to='Documents/',blank=True)
	producer_id=models.ForeignKey(Producers, on_delete=models.CASCADE)
	def __str__(self):
		return self.name
	class Meta:
		verbose_name = "Movies"
		verbose_name_plural = "Movies"
		unique_together = ('name', 'producer_id')

class ActorMovie(models.Model):
	actor_fk = models.ForeignKey(Actors, on_delete=models.CASCADE)
	movie_fk = models.ForeignKey(Movies, on_delete=models.CASCADE)
	def __str__(self):
		return '{}, {}'.format(self.actor_fk, self.movie_fk)
	class Meta:
		verbose_name = "ActorMovie"
		verbose_name_plural = "ActorMovie"
		unique_together = ('actor_fk', 'movie_fk')

imdb/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from imdb.models import *
# Create your views here.
def index(request):
	return render(request, 'imdb/index.html')

def movieDetails(request):
	return redirect('/admin/imdb/movies/')	

def addMovie(request):
	return redirect('/admin/imdb/movies/add/')

def moviesEdit(request):
	if request.method == 'POST':
		start_name=request.POST['movieName']
		movieNum=Movies.objects.get(name__iexact=start_name).pk
		return redirect('/admin/imdb/movies/%s/change/' %movieNum)

def editMovie(request):
	movieList=Movies.objects.all().values_list('name',flat=True)
	return render(request, 'imdb/movieEdit.html',{'movieList':movieList})

imdb/templates/imdb/index.html
<head>
	<title> IMDB.com</title>
</head>
<body>
	<h>Welcome to IMDB.com</h>
	<p>Search An Option</p>
	<!-- <input id="count" maxlength="100" name="count" type="text"/> -->
	<marquee>Welcome To IMDB.com</marquee>
	<p><a href="/imdb/movieDetails">Click to Fetch Movie Details</a></p>
	<p><a href="/imdb/addMovie">Click to Add new Movies</a></p>
	<p><a href="/imdb/editMovie">Click to Edit Movie Details</a></p>
</body>

imdb/templates/imdb/movieEdit.html
<html>
	<head>
		<title>Movie Edit</title>
	</head>
	<body>
		<form action="{% url 'imdb:moviesEdit' %}" method="post">
			{% csrf_token %}
		<!-- <form action="routeSearch" method="POST"> -->
		<p>Enter the Movie Name which you want to Edit</p>
		<select name="movieName">
		{% for movie in movieList %}
		<option value="{{ movie }}">{{movie}}</option>
		{% endfor %}
		</select>	
			<!-- <input type="text" name="movieName"/> --></br></br>
			<input type="submit" value="submit"/>
		</form>
	</body>
</html>